PREP(carAlarm);
PREP(carAlarmLoop);
PREP(carAlarmNotification);
PREP(createVehicle);
PREP(disableCarAlarm);
PREP(initCarAlarm);
PREP(initVehicles);
PREP(setVehicleRandomTexture);
PREP(vehicleStolenMsg);
