PREP(createCivilianMarker);
PREP(createCopMarker);
PREP(createKillerMarker);
PREP(createOrUpdateKillerMarker);
PREP(deleteUnitMarker);
PREP(markerDecay);
PREP(markerDecayLocal);
PREP(markerDecayLoop);
PREP(loop);
