PREP(appearsArmed);
PREP(getAllMapCities);
PREP(getLocationType);
PREP(getRandomEmptyPosition);
PREP(nearestLocation);
PREP(playMusicServer);
PREP(markerDecay);
PREP(markerDecayLoop);
PREP(showMessage);
