PREP(appearsArmed);
PREP(getAllMapCities);
PREP(getLocationType);
PREP(getRandomEmptyPosition);
PREP(getWeaponMagazines);
PREP(nearestLocation);
PREP(playMusicServer);
PREP(removeItemsFromArsenal);
PREP(showMessage);
